cask_args appdir: '/Applications'

brew 'curl'
brew 'lastpass-cli', args: ['with-pinentry']
brew 'postgresql'
brew 'shellcheck'
brew 'the_silver_searcher'
brew 'tree'
brew 'wget'

cask 'alacritty'
cask 'darktable'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'inkscape'
cask 'opera'
cask 'postman'
cask 'scribus'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'
