" PLUGINS

" Adding vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'morhetz/gruvbox'
Plug 'tpope/vim-surround'
Plug 'w0rp/ale'

" Initialize plugin system
call plug#end()

" OPTIONS

set nocompatible
syntax on
set number
set encoding=utf-8
let g:netrw_banner=0

" SEARCH
set hlsearch
set incsearch
set ignorecase
set smartcase

set background=dark
set t_Co=256
let g:gruvbox_contrast_dark="hard"
colorscheme gruvbox

" I don't like the forced wrap that `editorconfig-vim` provides,
" so I disable `max_line_length` and use `colorcolumn` instead.
let g:EditorConfig_disable_rules = ['max_line_length']
set colorcolumn=80

" REMAPS

" Disable arrow keys in normal mode
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
" Disable arrow keys in insert mode
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
" Disable hjkl keys in normal mode
nnoremap h <nop>
nnoremap j <nop>
nnoremap k <nop>
nnoremap l <nop>
" Map ctrl+p to open fzf
nnoremap <c-p> :FZF!<enter>

" FZF

" Customize fzf colors to match your color scheme
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" INSPIRATION
" https://dougblack.io/words/a-good-vimrc.html
" http://vimcasts.org/blog/2013/02/habit-breaking-habit-making/
